/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORTV_H_RPCGEN
#define _SORTV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
	int c;
};
typedef struct numbers numbers;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sort 1
extern  void * sort_1(int *, CLIENT *);
extern  void * sort_1_svc(int *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sort 1
extern  void * sort_1();
extern  void * sort_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORTV_H_RPCGEN */
